// 两端保持同一份逐项双语数据；英文正式，中文为 AI 参考译文。
const text = (en, zh) => ({ en, zh });
const item = (id, number, title, paragraphs, extra = {}) => ({ id, number, title, paragraphs, ...extra });
const link = (href, en, zh) => ({ href, label: text(en, zh) });

export const privacyPolicyMeta = {
  operator: 'ABDL-Space',
  contact: 'zhx589@outlook.com',
  version: '2026.10',
  updated: '2026-10-03',
  effective: '2026-10-03',
  minimumAge: 18,
  officialLanguage: 'en',
  defaultLanguage: 'zh',
};

export const privacyPolicyNotice = text(
  'The English version is the sole official version of this policy. The Chinese version is generated by AI translation and is for reference only. In case of any discrepancy, the English version prevails. Displaying Chinese by default does not change this rule.',
  '英文版本为本政策的唯一正式版本。中文版本由 AI 翻译生成，仅供参考；如有差异，以英文版本为准。默认展示中文不改变这一规则。',
);

export const privacyPolicySensitiveNotice = text(
  'Sensitive information: verification photos, body measurements, preferences and community content may reveal intimate or other sensitive details. Only provide what is necessary. Optional sensitive processing requires separate consent where required by law; reading this policy or continuing to use the service is not that consent. Public posts may be saved elsewhere, and private messages are not end-to-end encrypted.',
  '敏感信息提示：认证照片、身体测量、偏好与社区内容可能透露私密或其他敏感信息，请仅提供必要内容。可选的敏感信息处理应在法律要求时取得单独同意；阅读本政策或继续使用不等于该授权。公开帖子可能被外部保存，私信并非端到端加密。',
);

export const privacyPolicySections = [
  item('scope', '1', text('Scope, operator and adults only', '适用范围、运营名称与成年人限制'), [
    text('ABDL-Space (we/us) operates the diaper review and community service at abdl-space.top, m.abdl-space.top and its Android App, using a shared backend. This policy covers personal information processed through those services. Operator name: ABDL-Space. Contact: zhx589@outlook.com.', 'ABDL-Space（我们）运营 abdl-space.top、m.abdl-space.top 及 Android App 的纸尿裤评价与社区服务，使用共享后端。本政策适用于这些服务中的个人信息处理。运营名称：ABDL-Space。联系邮箱：zhx589@outlook.com。'),
    text('The service is only for adults aged 18 or older (18+). Anyone under 18 must not register or use it. Registration requires an adult declaration. If we learn of an underage account, we will stop its use and review deletion of related information, subject to necessary legal retention. A third party’s different age rule does not change our 18+ rule.', '本服务仅面向年满 18 周岁的成年人（18+）。未满 18 周岁不得注册或使用；注册须作出成年声明。发现未成年账户后，我们会停止其使用并审查删除相关信息，必要法律留存除外。第三方的不同年龄规则不改变本站 18+ 要求。'),
    text('Data processing depends on the feature and channel actually used. Availability varies between the App and web clients; the processing described for a feature applies when it is actually offered and used.', '数据处理取决于实际使用的功能与渠道，App 与网页端的功能可用性有所不同；各项处理以对应功能实际开放和使用为准。'),
  ]),
  item('account-community', '2', text('Accounts and community content', '账户与社区内容'), [], { children: [
    item('account-data', '2.1', text('Registration and optional profile', '注册与可选资料'), [
      text('Registration processes your email address, username and password hash. Optional profile fields include age, region, weight, waist and hip circumferences, preferences, biography and avatar. We use these for account management, profile display and the features you choose; body data and intimate preferences may be sensitive.', '注册会处理邮箱、用户名与密码哈希。可选资料包括年龄、地区、体重、腰围、臀围、偏好、简介和头像，用于账户管理、资料展示及您选择的功能；身体数据与私密偏好可能属于敏感信息。'),
    ]),
    item('community-data', '2.2', text('Posts, messages and reports', '帖子、私信与举报'), [
      text('We process posts, comments, ratings, usage reviews, private messages, reports and interactions such as likes and follows to provide community communication, moderation and safety. Public profiles and published content may be viewed, copied, indexed or saved by others outside our control. Private messages are not end-to-end encrypted; service delivery and authorized safety handling involve server-side processing.', '我们处理帖子、评论、评分、使用感受、私信、举报及点赞、关注等互动，用于社区交流、审核与安全管理。公开资料和已发布内容可能被他人在本站控制范围之外查看、复制、索引或保存。私信并非端到端加密，消息投递与授权安全处理涉及服务端处理。'),
    ]),
  ] }),
  item('qq', '3', text('Optional QQ login and linking', '可选 QQ 登录与绑定'), [
    text('The Android App uses Tencent QQ Connect 3.5.19 lite, operated by Shenzhen Tencent Computer Systems Company Limited (深圳市腾讯计算机系统有限公司). It is called for login or linking only after you actively select QQ login/linking and confirm. Authorization code and access token are used temporarily to obtain OpenID, UnionID, nickname and avatar. The SDK also processes device model information for its reporting, issue monitoring and compatibility troubleshooting.', 'Android App 使用腾讯 QQ 互联 Connect 3.5.19 lite，运营主体为深圳市腾讯计算机系统有限公司。仅在您主动选择 QQ 登录或绑定并确认后，为登录或绑定调用。授权 code 与 access token 临时用于换取 OpenID、UnionID、昵称及头像；SDK 还为上报、问题监控及兼容性排查处理设备型号信息。'),
    text('The server stores HMAC-protected identifier mappings, including mappings created even if linking is not completed, and stores linked nickname, avatar and binding time. HMAC protection is not anonymization: these mappings can still associate an authorization with an account. Raw QQ tokens are not retained long term. Our use is account login and association, not sharing or other unused SDK scenarios; permissions described for those scenarios should not all be treated as collection currently performed by this service.', '服务端存储 HMAC 化标识映射（即使未完成绑定也可能生成并保存），以及绑定昵称、头像和绑定时间。HMAC 保护不是匿名化：这些映射仍能将授权与账户关联。原始 QQ token 不长期保存。本站用途为登录与账户关联，不是分享等未使用的 SDK 场景；不能把这些场景的权限全部视为本站当前采集。'),
    text('Unlinking removes the site-side QQ binding and its corresponding identifier mapping. You may need another working login method to retain account access. Unlinking here is not revocation of Tencent authorization; manage Tencent-side authorization through Tencent separately. For unresolved mappings or deletion requests, contact us.', '解绑会清除本站 QQ 绑定及对应标识映射；为保持账户可访问，您可能需要其他可用登录方式。本站解绑不等于撤销腾讯授权，腾讯侧授权需另行在腾讯管理。未解决的映射或删除请求请联系本站。'),
  ], { service: true, links: [
    link('https://wiki.connect.qq.com/qq互联sdk隐私保护声明', 'QQ SDK privacy statement', 'QQ SDK 隐私保护声明'),
    link('https://wiki.connect.qq.com/开发者协议', 'QQ developer agreement', 'QQ 开发者协议'),
    link('https://privacy.qq.com/', 'Tencent privacy', '腾讯隐私政策'),
  ] }),
  item('nbw', '4', text('Optional NewBabyWorld integration', '可选宝宝新天地集成'), [
    text('NewBabyWorld (NBW, newbabyworld.top) is an independently operated third party, not operated by ABDL-Space. Its OAuth flow provides UID, username and avatar; one-click registration may also provide an email address. Email lookup/registration sends the email address to NBW. We store the NBW UID and username to create or link an account.', '宝宝新天地（NBW，newbabyworld.top）是独立运营的第三方，并非由 ABDL-Space 运营。OAuth 流程提供 UID、用户名和头像，一键注册还可能提供邮箱；邮箱查询或注册会将邮箱发送给 NBW。本站存储 NBW UID 和用户名，用于创建或关联账户。'),
    text('After linking, post titles, bodies and images may be cross-posted to NBW by default. The first 500 characters of the NBW post body may be sent to DeepSeek to select a forum category. The App’s disable option alone cannot reliably confirm that all cross-posting has stopped. If you do not want content sent to NBW, first unlink and confirm the binding has been removed before posting; contact us if you are unsure.', '绑定后，帖子标题、正文和图片可能默认双发至 NBW；NBW 帖子正文前 500 字符可能发送给 DeepSeek 选择分区。仅凭 App 的关闭选项不能可靠确认已停止全部双发。如不希望内容发送至 NBW，请先解绑并确认绑定已移除，再发布内容；不确定时请联系本站。'),
    text('Unlinking does not delete your NBW account or copies already posted there. Handle third-party copies with NBW. NBW’s policy dated 2024-08-05 lists admin@mail.newbabyworld.top and a 14+ age rule. That is NBW’s independent rule, not ours: ABDL-Space remains 18+. Refer to NBW’s homepage or contact NBW for its current policy.', '解绑不会删除 NBW 账户或已发布到该平台的副本，第三方副本需向 NBW 处理。宝宝新天地 2024-08-05 政策列明联系邮箱 admin@mail.newbabyworld.top 与 14+ 年龄规则。这是 NBW 的独立规则，本站仍为 18+。现行政策请访问 NBW 主页或联系 NBW 查询。'),
  ], { service: true, links: [link('https://newbabyworld.top', 'NBW homepage', 'NBW 主页'), link('mailto:admin@mail.newbabyworld.top', 'Contact NBW', '联系 NBW')] }),
  item('verification', '5', text('Optional baby verification', '可选宝宝认证'), [], { sensitive: true, children: [
    item('verification-submission', '5.1', text('Photos and review records', '照片与审核记录'), [
      text('When you actively apply, a complete photo is uploaded to Tencent Cloud COS; this is not hash-only storage. We process the review contact QQ number (encrypted with AES-GCM), your adult declaration with its time and policy version, random shooting requirements, the photo’s SHA-256, size and object key, review status, remarks, reviewer and review time. Photos and body information are sensitive: they are necessary for this optional review and require separate consent. Do not submit unrelated sensitive details.', '您主动申请时，完整照片会上传至腾讯云 COS，并非只保存哈希。处理数据包括审核联系 QQ 号码（AES-GCM 加密）、成年声明及其时间和政策版本、随机拍摄要求、照片 SHA-256、大小和对象键，以及审核状态、备注、审核人员和审核时间。照片与身体信息属于敏感信息，是该可选审核所必需的数据，应取得单独同意；请勿提交无关敏感内容。'),
      text('This is community verification, not identity-card real-name verification, facial recognition or a medical assessment. Authorized administrators can read photos through short-lived signed URLs for review. Public certificates expose username, verification status and issue time, not the verification photo or contact QQ number. We do not publish verification photos or use them for advertising.', '这是社区认证，不是身份证实名验证、人脸识别或医学鉴定。授权管理员通过短期签名链接读取照片进行审核；公开证书展示用户名、认证状态与签发时间，不公开认证照片或联系 QQ 号码。我们不将认证照片公开或用于广告。'),
    ]),
    item('verification-retention', '5.2', text('Local drafts and deletion limits', '本地草稿与删除局限'), [
      text('The App re-encodes photos to remove EXIF and uses a noBackup directory for local drafts/cache. A failed submission can leave a draft; success or abandonment clears the draft/cache. We do not claim all caches are encrypted. Cancellation, rejection or revocation does not itself delete uploaded photos. There is no unified automatic photo destruction schedule or promised number of retention days. Request deletion by email; we review the necessary scope, legal retention and backup cleanup separately.', 'App 重编码照片以清除 EXIF，并使用 noBackup 目录存放本地草稿或缓存。提交失败可能保留草稿；成功或放弃时清理草稿或缓存。不声称全部缓存均已加密。取消、拒绝或吊销认证本身不等于删除已上传照片。目前没有统一的照片自动销毁机制或承诺的保留天数。请通过邮箱申请删除，我们分别审查必要范围、法律留存和备份清理。'),
    ]),
  ] }),
  item('authentication', '6', text('Local lock and passkeys', '本地锁与通行密钥'), [], { children: [
    item('local-lock', '6.1', text('PIN and system biometrics', 'PIN 与系统生物识别'), [
      text('The App’s local PIN protection uses Android Keystore encryption. System BiometricPrompt handles biometric authentication; ABDL-Space does not receive fingerprint or face templates. The 2FAS open-source lock module is a local lock component, not TOTP two-factor authentication or a third-party verification service.', 'App 本地 PIN 保护使用 Android Keystore 加密，系统 BiometricPrompt 处理生物识别认证；ABDL-Space 不接收指纹或面容模板。2FAS 开源锁模块是本地锁组件，不是 TOTP 双因素认证或第三方验证服务。'),
    ]),
    item('passkeys', '6.2', text('Passkey registration', 'Passkey 注册'), [
      text('For passkeys, the server stores credential ID, public key, counter, device type, backup status, transports, nickname and relevant times. The private key is managed by your system/authenticator, not stored by our server. These records support authentication and credential management.', '使用 Passkey 时，服务端存储 credential ID、公钥、counter、设备类型、备份状态、transport、昵称与相关时间，用于认证和凭据管理。私钥由系统或认证器管理，不由本站服务端保存。'),
    ]),
  ] }),
  item('notifications', '7', text('Push and compatible clients', '推送与兼容客户端'), [], { children: [
    item('jiguang', '7.1', text('JPush / JCore / JOperate', '极光 JPush / JCore / JOperate'), [
      text('JPush, JCore and JOperate initialize at App startup, not only after login consent. We associate a registration ID (regId) with an account and creation/activity times. Notification title, body and navigation destination are sent to Jiguang for delivery. Depending on SDK version and configuration, the SDK may process identifiers such as Android ID/OAID, device model, operating system, network information, IP address and optional application information; this does not mean every listed field is always collected.', 'JPush、JCore 与 JOperate 会在 App 启动时初始化，并非仅在登录同意后初始化。本站关联注册标识 regId、账号及创建或活跃时间，并将通知标题、正文和跳转目标发送给极光进行投递。SDK 随版本和配置可能处理 Android ID、OAID 等标识、机型、系统、网络信息、IP 及可选应用信息，并非列出的每项始终必采。'),
      text('Turning off system notifications stops their display; it does not by itself stop SDK initialization or data processing. Review system permissions and available channel settings, and contact us about withdrawal or deletion requests.', '关闭系统通知仅停止通知展示，本身不等于停止 SDK 初始化或数据处理。请审查系统权限及可用通道设置，撤回或删除请求可联系本站。'),
    ], { service: true, links: [link('https://www.jiguang.cn/license/privacy', 'Jiguang privacy', '极光隐私政策')] }),
    item('compatible-push', '7.2', text('FCM, relay and WebPush status', 'FCM、relay 与 WebPush 状态'), [
      text('On GMS-capable devices, the App may request an FCM token and construct a compatible relay endpoint using app.joinmastodon.org. Compatible-client subscriptions can store endpoint, public key, authentication secret and settings; the channel actually enabled handles delivery. Complete server-side WebPush delivery is not yet implemented, so these capabilities must not be read as fully launched push channels.', '在支持 GMS 的设备上，App 可请求 FCM token，并使用 app.joinmastodon.org 构造兼容 relay endpoint。兼容客户端订阅可保存 endpoint、公钥、认证密钥和设置，由实际开通的通道处理投递。服务端完整 WebPush 投递尚未完成，这些能力不表示所有推送通道已全面上线。'),
      text('If you authorize a third-party Mastodon-compatible client, an OAuth access token allows it to access your account within its authorization scope. The client and any enabled push relay process data under their own terms. Review their permissions and policies before authorization; withdrawing authorization does not erase copies they already hold.', '您授权第三方 Mastodon 兼容客户端时，OAuth access token 使其在授权范围内访问账户。客户端及实际启用的推送 relay 按各自条款处理数据。授权前请核查权限与政策；撤销授权不清除其已持有副本。'),
    ], { service: true }),
  ] }),
  item('technical', '8', text('Technical data, security and local storage', '技术信息、安全与本地存储'), [], { children: [
    item('security-logs', '8.1', text('Requests and abuse prevention', '请求与防滥用'), [
      text('Requests and safety systems may process IP address, User-Agent, request path and time, captcha-related behavior, screen information and time zone. Rate limiting, QR-code scanning controls, bans and targeted tracing of particular anomalous accounts support abuse prevention and troubleshooting. We do not represent that all IP addresses are stored permanently or that all logs are automatically deleted after the same short period.', '请求与安全系统可能处理 IP、User-Agent、请求路径和时间、验证码相关行为、屏幕信息与时区。限流、扫码控制、封禁及对特定异常账户的针对性追踪用于防滥用和排障。不声称所有 IP 永久保存，也不声称所有日志在统一短期后自动删除。'),
    ]),
    item('app-version', '8.2', text('App compatibility and version records', 'App 兼容与版本记录'), [
      text('App requests carry a version name in the User-Agent and X-App-Version-Code for compatibility and upgrade handling. When native-client version recording is actually offered, first/latest version and access time are recorded by account for compatibility and upgrade support. Our version records do not use IMEI or an advertising tracking ID.', 'App 请求通过 User-Agent 中的版本名和 X-App-Version-Code 支持兼容与升级。在原生客户端版本记录功能实际开放后，会按账号记录首次、最近版本和访问时间，用于兼容与升级支持。本站版本记录不使用 IMEI 或广告跟踪 ID。'),
    ]),
    item('local-storage', '8.3', text('Cookies, preferences and drafts', 'Cookies、偏好与草稿'), [
      text('Cookies and local storage support login, preferences, drafts and caches; web analytics may also use cookies. Browser cookie controls, local-data clearing and system permissions affect these functions and may sign you out or remove unsent drafts. Clearing local data does not delete server records. We make no blanket promise of no advertising identifiers, no location processing or no device fingerprinting across all service and SDK activity.', 'Cookies 与本地存储用于登录、偏好、草稿和缓存，网页统计也可能使用 cookies。浏览器 cookie 控制、本地数据清理及系统权限会影响这些功能，可能导致退出登录或丢失未发送草稿。清理本地数据不删除服务端记录。不对服务及 SDK 的全部活动作出绝对无广告标识、不处理位置或无设备指纹的承诺。'),
    ]),
  ] }),
  item('payments', '9', text('Paid plans and external checkout', '付费计划与外部结账'), [
    text('Checkout takes place externally at ifdian.net. ABDL-Space does not receive your payment card details or payment password through that checkout. We process plan codes (including hashed, masked and encrypted recoverable ciphertext forms), account, redemption time, validity period, entitlements, original-image quota, authorization notices and operation audit records to deliver paid benefits and manage misuse. Administration may involve order numbers and reply-based verification.', '结账在 ifdian.net 外部进行，本站不通过该结账接收支付卡信息或支付密码。为交付付费权益和防止滥用，我们处理计划码（包括哈希、掩码与可恢复的加密密文形式）、账号、兑换时间、有效期、权益、原图额度、授权须知及操作审计记录；后台可能涉及订单号和回复核验。'),
    text('The payment platform independently handles checkout data under its own terms. Refunds depend on applicable law and the order terms; this policy does not promise an unconditional refund or automatic deletion of required transaction records.', '支付平台按其自身条款独立处理结账数据。退款按适用法律与订单条款办理；本政策不承诺无条件退款或自动删除必要交易记录。'),
  ], { service: true, links: [link('https://ifdian.net', 'Checkout platform', '结账平台')] }),
  item('reading', '10', text('Novel import, reading and creation', '小说导入、阅读与创作'), [
    text('TXT/EPUB import uploads the complete file to COS, together with metadata such as a SHA-256 file checksum, title, author, format and size. Chapters are parsed locally, but the feature is not purely local. Reading progress, bookmarks and notes synchronize to the server. Creative writing bodies are stored in D1 and become public when published.', 'TXT、EPUB 导入会将完整文件上传至 COS，并处理 SHA-256 文件校验摘要、标题、作者、格式和大小等元数据。章节在本地解析，但该功能并非纯本地。阅读进度、书签与笔记会同步到服务端；创作正文存储于 D1，发布后公开。'),
    text('Deletion uses soft deletion and asynchronous object cleanup; it is not immediate destruction of every file or backup. Imported files are not intended for arbitrary public disclosure by the platform, but storage and transmission cannot be guaranteed absolutely secure. Do not import files containing unnecessary sensitive information or content you are not entitled to upload.', '删除采用软删除与异步对象清理，并非立即销毁每个文件或备份。导入文件不供平台任意公开，但存储与传输不能保证绝对安全。请勿导入含不必要敏感信息或无权上传内容的文件。'),
  ]),
  item('ai', '11', text('Optional DeepSeek processing', '可选 DeepSeek 处理'), [
    text('When you choose AI recommendations, request data sent to DeepSeek may include selected profile information such as age, region, body measurements, preferences and biography, plus aggregated usage reviews. Not all request fields are controlled by selection checkboxes: usage-review summaries are also included. The request is sent when you use the feature, not through automatic daily listening or continuous monitoring. You can choose not to use it; sensitive information requires separate consent where applicable.', '您选择 AI 推荐时，发送至 DeepSeek 的请求数据可能包括按选择提供的年龄、地区、身体测量、偏好与简介等资料，以及使用感受汇总。并非所有请求字段都受勾选控制，使用感受汇总也会包含在内。请求在使用功能时发送，不进行自动日常监听或持续监控。您可以不使用该功能；敏感信息处理应在适用时取得单独同意。'),
    text('NBW cross-posting separately sends the first 500 characters of its post body to DeepSeek for category selection as described in section 4. DeepSeek processes received data under its own applicable terms; avoid including unrelated private details in either request. Visit its official site for current terms and privacy information.', 'NBW 双发还会按第 4 节所述，将其帖子正文前 500 字符发送至 DeepSeek 选择分区。DeepSeek 按其适用条款处理所接收数据，请避免在两类请求中包含无关私密信息。现行条款与隐私说明请访问其官网查询。'),
  ], { service: true, sensitive: true, links: [link('https://www.deepseek.com', 'DeepSeek official site', 'DeepSeek 官网')] }),
  item('location-analytics', '12', text('Location and website analytics', '位置与网页统计'), [], { children: [
    item('tianditu', '12.1', text('System location and Tianditu', '系统定位与天地图'), [
      text('When you use location selection and grant system location permission, coordinates are sent to Tianditu for reverse geocoding. The region is cached locally, and a post’s region can be uploaded with the post. This may involve sensitive location data. You can deny system location permission or avoid the feature; withdrawal does not itself remove regions already posted.', '您使用定位选择并授予系统定位权限时，坐标发送至天地图进行逆地理编码。地区在本地缓存，帖子地区可随帖子上传，可能涉及敏感位置信息。您可拒绝系统定位权限或不使用该功能；撤回本身不移除已发布地区。'),
      text('Visit Tianditu’s official site for its service terms and privacy information.', '服务条款与隐私说明请访问天地图官网查询。'),
    ], { service: true, sensitive: true, links: [link('https://www.tianditu.gov.cn', 'Tianditu official site', '天地图官网')] }),
    item('baidu', '12.2', text('IP region and Baidu Analytics', 'IP 属地与百度统计'), [
      text('An IP address may be sent to Baidu Maps for IP-region resolution. On web pages, Baidu Analytics uses cookies and may process device and browsing data such as page visits, referrals and browser/system information for usage analysis. It is a third-party processing activity, not a guarantee of anonymous data. Browser cookie or script-blocking controls can limit analytics, but may affect functionality and do not erase data already received.', 'IP 地址可能发送给百度地图用于解析 IP 属地。网页上的百度统计使用 cookies，并可能处理页面访问、来源、浏览器、系统等设备与浏览数据，用于使用分析。这属于第三方处理，并不保证数据匿名。浏览器 cookie 或脚本拦截控制可以限制统计，但可能影响功能，且不清除已接收数据。'),
    ], { service: true, links: [link('https://privacy.baidu.com/policy', 'Baidu privacy', '百度隐私政策')] }),
  ] }),
  item('providers-disclosure', '13', text('Infrastructure and disclosure roles', '基础服务与披露角色'), [], { children: [
    item('cloudflare', '13.1', text('Cloudflare hosting and security', 'Cloudflare 托管与安全'), [
      text('Cloudflare Pages, Workers, D1, KV, Durable Objects (DO) and Queues provide edge hosting, databases, storage, coordination, queues and security. They may process IP addresses, request content, database content and logs to operate these services. Distributed edge processing may transfer data across borders; not all data is guaranteed to stay in China. Cross-border processing is subject to applicable legal requirements and safeguards.', 'Cloudflare Pages、Workers、D1、KV、Durable Objects（DO）和 Queues 提供边缘托管、数据库、存储、协调、队列与安全服务，可能为运行服务处理 IP、请求内容、数据库内容与日志。分布式边缘处理可能涉及跨境传输，不保证全部数据留在中国。跨境处理须遵循适用法律要求与保障措施。'),
    ], { service: true, links: [link('https://www.cloudflare.com/privacypolicy/', 'Cloudflare privacy', 'Cloudflare 隐私政策')] }),
    item('tencent-cloud', '13.2', text('Tencent Cloud COS and SES', '腾讯云 COS 与 SES'), [
      text('Tencent Cloud COS in Shanghai stores images, media, verification photos and novels. Tencent Cloud SES processes email addresses and email contents for service email delivery. Infrastructure providers handle the data needed for their services; their policies also govern their own processing.', '上海地域的腾讯云 COS 存储图像、媒体、认证照片与小说。腾讯云 SES 为服务邮件投递处理邮箱地址与邮件内容。基础服务商处理其服务所需数据，自身处理也受其政策约束。'),
    ], { service: true, links: [link('https://cloud.tencent.com/document/product/301/1140', 'Tencent Cloud privacy', '腾讯云隐私政策')] }),
    item('disclosure-roles', '13.3', text('Entrusted, independent and public processing', '委托处理、独立处理与用户公开'), [
      text('We distinguish providers processing data for our hosting/delivery tasks from independent services you authorize or visit, and from information you choose to publish. QQ, NBW, external checkout, authorized clients and provider SDKs may also perform their own processing under their terms. The service cards explain triggers, data and purposes; third-party policies should be reviewed separately. External links are not a promise that the third party has identical safeguards.', '我们区分为本站托管或投递任务处理数据的服务商、您授权或访问的独立服务，以及您自行公开的信息。QQ、NBW、外部结账、授权客户端及服务商 SDK 也可能按各自条款进行自身处理。服务卡片说明触发场景、数据与目的，第三方政策需另行阅读。外部链接不表示第三方拥有与本站完全相同的保障。'),
      text('We do not sell personal information. We do not publish verification photos or use them for advertising. Necessary disclosures may occur for lawful requests, safety and abuse investigations or legal obligations, limited to the relevant purpose and necessary scope.', '我们不出售个人信息，不公开认证照片或将其用于广告。依法提出的要求、安全与滥用调查或法律义务可能需要披露，应限定在相关目的与必要范围内。'),
    ]),
  ] }),
  item('security-retention', '14', text('Security, retention and processing grounds', '安全、保留与处理依据'), [], { children: [
    item('security-measures', '14.1', text('Safeguards and limitations', '保障措施与局限'), [
      text('Measures include password hashing, HTTPS/TLS, access controls, HMAC-protected QQ identifiers, encrypted review contact QQ numbers and short-lived signed review links. These measures reduce risk but do not guarantee absolute security, anonymization, encrypted storage of every cache or end-to-end encrypted messaging.', '措施包括密码哈希、HTTPS/TLS、访问控制、HMAC 化 QQ 标识、审核联系 QQ 号码加密与短期签名审核链接。这些措施降低风险，但不保证绝对安全、匿名化、每份缓存均加密或私信端到端加密。'),
    ]),
    item('retention', '14.2', text('Necessary retention, not a fixed deadline', '必要留存，而非固定期限'), [
      text('Account, community, verification, transaction and security records are retained according to their service purposes, necessary safety or legal needs and deletion reviews. We have no unified automatic cleanup schedule for photos and logs and promise no fixed number of retention days. Stopping a feature or unlinking an account does not erase all historical records. Deletion may involve soft deletion, asynchronous object removal and gradual backup cleanup; necessary legal records may be retained separately. Public or third-party copies are outside our direct deletion control.', '账户、社区、认证、交易与安全记录按服务目的、必要安全或法律需要及删除审查保留。目前照片与日志没有统一自动清理机制，不承诺固定保留天数。停止功能或解绑不清除全部历史记录。删除可能涉及软删除、异步对象移除与备份逐步清理；必要法律记录可能单独留存。公开或第三方副本不在本站直接删除控制范围内。'),
    ]),
    item('legal-grounds', '14.3', text('Applicable legal grounds', '适用的法律依据'), [
      text('Depending on applicable law and the processing involved, grounds may include providing a service you request, consent, legal obligations and necessary security interests. Where EEA/UK law applies, relevant GDPR grounds may include Article 6(1)(a), (b), (c) or (f); sensitive data requires an applicable additional condition where required. Optional sensitive processing needs the required specific consent, not presumed consent from continued use.', '按适用法律与具体处理，依据可能包括提供您请求的服务、同意、法律义务和必要安全利益。适用欧洲经济区或英国法律时，相关 GDPR 依据可能包括第 6 条第 1 款 (a)、(b)、(c) 或 (f) 项；敏感数据在要求时还需适用的额外条件。可选敏感处理需要所要求的特定同意，不以继续使用推定授权。'),
    ]),
  ] }),
  item('rights', '15', text('Your choices and rights requests', '您的选择与权利申请'), [
    text('Contact zhx589@outlook.com to request access, correction, deletion, a copy/export of your information, account closure, withdrawal of consent or to complain. We may verify account ownership proportionately before responding. Complete self-service account closure and export are not currently available; please request them by email. Clicking a control does not mean the request has been fully completed or every record, object and backup immediately destroyed. We review deletion requests within the necessary scope and explain applicable legal retention, third-party copies and backup cleanup limits.', '请联系 zhx589@outlook.com 申请查阅、更正、删除、获取信息副本或导出、注销账户、撤回同意或投诉。处理前可能进行适度的账户身份核验。目前尚未提供完整的自助注销与导出，请通过邮箱申请。点击相关控件不意味着申请已经全部办结，或全部记录、对象与备份立即销毁。我们按必要范围审查删除申请，并说明适用法律留存、第三方副本和备份清理的局限。'),
    text('You can stop optional features, revoke system permissions and use available unlink/authorization controls, subject to the limitations stated above (especially NBW cross-posting and push SDK initialization). Withdrawal affects future processing based on that consent, not the lawfulness of prior processing, and does not itself clear all history. Ask the independent third party to handle copies it holds.', '您可停止可选功能、撤回系统权限及使用可用解绑或授权控制，但须注意前述局限，特别是 NBW 双发与推送 SDK 初始化。撤回影响今后基于该同意的处理，不影响此前处理的合法性，本身也不清除全部历史。独立第三方持有的副本需向该第三方处理。'),
    text('Where applicable, EEA/UK users may also request restriction, object, seek portability or complain to a supervisory authority; California users may have rights to know, delete, correct and opt out of legally defined sale/sharing. We do not sell personal information, but do not use this statement as a blanket legal classification of all SDK/analytics activity. Rights and exceptions depend on applicable law. If you believe an underage account or improper sensitive processing exists, report it by email.', '适用时，欧洲经济区或英国用户还可申请限制处理、反对、数据可携或向监管机构投诉；加利福尼亚用户可能享有知情、删除、更正及退出法律定义的出售或共享的权利。我们不出售个人信息，但不以此对全部 SDK 或统计活动作出笼统法律定性。权利与例外取决于适用法律。如发现未成年账户或不当敏感信息处理，请通过邮箱反馈。'),
  ], { links: [link('mailto:zhx589@outlook.com', 'Send a rights request', '发送权利申请')] }),
  item('changes-contact', '16', text('Policy changes and contact', '政策变更与联系'), [
    text('Version 2026.10 was updated and takes effect on 2026-10-03. Material changes will be communicated through this page and appropriate site announcements or in-app notices. Where required, we will seek consent again before new processing, especially sensitive processing. Continued use is not a substitute for required separate consent. Updating this policy alone does not mean new authorization has been obtained.', '版本 2026.10 于 2026-10-03 更新并生效。重大变更将通过本页及适当的网站公告或应用内通知告知。法律要求时，我们会在新的处理前重新取得同意，尤其是敏感信息处理。继续使用不能替代所要求的单独同意；仅更新政策不代表已获得新的授权。'),
    text('Operator name: ABDL-Space. For privacy questions, rights requests and complaints, email zhx589@outlook.com. Please describe the account, relevant feature and request without sending unnecessary photos, passwords or payment secrets.', '运营名称：ABDL-Space。隐私问题、权利申请与投诉请发送至 zhx589@outlook.com。请说明账户、相关功能与请求，不要发送不必要的照片、密码或支付密钥。'),
  ], { links: [link('mailto:zhx589@outlook.com', 'Contact ABDL-Space', '联系 ABDL-Space')] }),
];

// 目录包含每个章节和子章节；同一锚点在语言切换后保持有效。
export const privacyPolicyContents = privacyPolicySections.flatMap(section => [
  { id: section.id, number: section.number, title: section.title },
  ...(section.children || []).map(child => ({ id: child.id, number: child.number, title: child.title })),
]);
